### ISSUE TITLE
How can I embedded calendar in html?

### ISSUE THREAD

**Issue by arjunskumar** [x3388638/github-calendar-graph#10]
I have trouble embedding calendar to my GitHub page. Could you provide some tips?

**Comment by x3388638** [comment]
To use this package, you need a node server to crawl the calendar and then append the result to HTML.

something like this at the server side
```
app.get('/:account', (req, res) => {
        const { account } = req.params;
        CalendarGraph.fetch(account).then((graph) => {
                res.send(graph);
        });
});
```
fetch it and append to your DOM at client side

To integrate into GitHub page, you need to set up another server to serve this, or there are some other awesome alternative packages on the GitHub.

**Comment by x3388638** [comment]
Provided a simple example
https://github.com/x3388638/github-calendar-graph/tree/master/example

**Comment by x3388638** [comment]
If any more questions, feel free to reopen it.

**Comment by arjunskumar** [comment]
@x3388638  I couldn't make it. Thanks
